const data = `{
"1": {
    "itemDetails": {
    "id": "1",
    "parent_id": null,
    "tags": "project",
    "title": "Cross-Functional Project 1",
    "content": "A sample website development project that begins with complete scratch.",
    "status": "backlog",
    "next_progressive_status": "in-progress",
    "assigned_to": "john",
    "importance": null,
    "added_value": null,
    "proposed_start": null,
    "proposed_end": null,
    "estimated_start": null,
    "estimated_end": null,
    "actual_start": null,
    "actual_end": null,
    "proposed_duration_timestamp": null,
    "estimated_duration_timestamp": null,
    "actual_duration_timestamp": null,
    "progress": "0",
    "priority_score": "0"
    },
    "parents": [],
    "children": {
    "2": {
        "itemDetails": {
        "id": "2",
        "parent_id": "1",
        "tags": "folder",
        "title": "Planning",
        "content": null,
        "status": "backlog",
        "next_progressive_status":  "in-progress",
        "assigned_to": "john",
        "importance": null,
        "added_value": null,
        "proposed_start": null,
        "proposed_end": null,
        "estimated_start": null,
        "estimated_end": null,
        "actual_start": null,
        "actual_end": null,
        "proposed_duration_timestamp": null,
        "estimated_duration_timestamp": null,
        "actual_duration_timestamp": null,
        "progress": "0",
        "priority_score": "0"
        },
        "parents": [],
        "children": {
        "3": {
            "itemDetails": {
            "id": "3",
            "parent_id": "2",
            "tags": "task",
            "title": "Finalize the requirements with client",
            "content": null,
            "status": "in-progress",
            "next_progressive_status":  "done",
            "assigned_to": "john",
            "importance": "10",
            "added_value": "10",
            "proposed_start": null,
            "proposed_end": null,
            "estimated_start": "2022-06-19 00:01:00",
            "estimated_end": "2022-06-20 23:59:00",
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": "7200",
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "152.99931318681"
            },
            "children": []
        },
        "5": {
            "itemDetails": {
            "id": "5",
            "parent_id": "2",
            "tags": "task",
            "title": "Finalize budget",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": "2022-06-24 23:59:00",
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": "7200",
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "2.9993131868132"
            },
            "children": []
        },
        "6": {
            "itemDetails": {
            "id": "6",
            "parent_id": "2",
            "tags": "task",
            "title": "Evaluate new email marketing platform",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": "2022-06-24 23:59:00",
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": []
        },
        "18": {
            "itemDetails": {
            "id": "18",
            "parent_id": "2",
            "tags": "task",
            "title": "Proof read contents for website",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": "2022-07-15 23:59:00",
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": []
        }
        }
    },
    "7": {
        "itemDetails": {
        "id": "7",
        "parent_id": "1",
        "tags": "folder",
        "title": "Design",
        "content": null,
        "status": "backlog",
        "next_progressive_status":  "in-progress",
        "assigned_to": "john",
        "importance": null,
        "added_value": null,
        "proposed_start": null,
        "proposed_end": null,
        "estimated_start": null,
        "estimated_end": null,
        "actual_start": null,
        "actual_end": null,
        "proposed_duration_timestamp": null,
        "estimated_duration_timestamp": null,
        "actual_duration_timestamp": null,
        "progress": "0",
        "priority_score": "0"
        },
        "parents": [],
        "children": {
        "4": {
            "itemDetails": {
            "id": "4",
            "parent_id": "7",
            "tags": "task",
            "title": "Design the mock-ups",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": "2022-06-26 00:01:00",
            "proposed_end": "2022-06-27 23:59:00",
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": "36000",
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "2.9965659340659"
            },
            "children": []
        },
        "14": {
            "itemDetails": {
            "id": "14",
            "parent_id": "7",
            "tags": "milestone",
            "title": "Start designing pages",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": null,
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": []
        },
        "15": {
            "itemDetails": {
            "id": "15",
            "parent_id": "7",
            "tags": "task",
            "title": "Design landing page",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": "2022-06-26 00:01:00",
            "proposed_end": "2022-06-27 23:59:00",
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": "36000",
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "2.9965659340659"
            },
            "children": []
        },
        "16": {
            "itemDetails": {
            "id": "16",
            "parent_id": "7",
            "tags": "task",
            "title": "Design store page",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": "2022-06-28 00:01:00",
            "proposed_end": "2022-06-29 23:59:00",
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": "18000",
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "2.998282967033"
            },
            "children": []
        },
        "17": {
            "itemDetails": {
            "id": "17",
            "parent_id": "7",
            "tags": "task",
            "title": "Design checkout page",
            "content": " ",
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": null,
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": []
        }
        }
    },
    "8": {
        "itemDetails": {
        "id": "8",
        "parent_id": "1",
        "tags": "folder",
        "title": "Development",
        "content": null,
        "status": "backlog",
        "next_progressive_status":  "in-progress",
        "assigned_to": "john",
        "importance": null,
        "added_value": null,
        "proposed_start": null,
        "proposed_end": null,
        "estimated_start": null,
        "estimated_end": null,
        "actual_start": null,
        "actual_end": null,
        "proposed_duration_timestamp": null,
        "estimated_duration_timestamp": null,
        "actual_duration_timestamp": null,
        "progress": "0",
        "priority_score": "0"
        },
        "parents": [],
        "children": {
        "11": {
            "itemDetails": {
            "id": "11",
            "parent_id": "8",
            "tags": "objective",
            "title": "Develop Website",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": "2022-06-26 00:01:00",
            "proposed_end": "2022-07-31 23:59:00",
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": {
            "13": {
                "itemDetails": {
                "id": "13",
                "parent_id": "11",
                "tags": "project",
                "title": "Convert the designs to web designs",
                "content": null,
                "status": "backlog",
                "next_progressive_status":  "in-progress",
                "assigned_to": "john",
                "importance": null,
                "added_value": null,
                "proposed_start": "2022-07-03 00:01:00",
                "proposed_end": "2022-07-15 23:59:00",
                "estimated_start": null,
                "estimated_end": null,
                "actual_start": null,
                "actual_end": null,
                "proposed_duration_timestamp": "180000",
                "estimated_duration_timestamp": null,
                "actual_duration_timestamp": null,
                "progress": "0",
                "priority_score": "2.9828296703297"
                },
                "parents": [],
                "children": []
            },
            "19": {
                "itemDetails": {
                "id": "19",
                "parent_id": "11",
                "tags": "task",
                "title": "Create the landing page",
                "content": null,
                "status": "backlog",
                "next_progressive_status":  "in-progress",
                "assigned_to": "john",
                "importance": null,
                "added_value": null,
                "proposed_start": null,
                "proposed_end": null,
                "estimated_start": null,
                "estimated_end": null,
                "actual_start": null,
                "actual_end": null,
                "proposed_duration_timestamp": null,
                "estimated_duration_timestamp": null,
                "actual_duration_timestamp": null,
                "progress": "0",
                "priority_score": "0"
                },
                "parents": [],
                "children": []
            },
            "20": {
                "itemDetails": {
                "id": "20",
                "parent_id": "11",
                "tags": "task",
                "title": "Create the store page",
                "content": null,
                "status": "backlog",
                "next_progressive_status":  "in-progress",
                "assigned_to": "john",
                "importance": null,
                "added_value": null,
                "proposed_start": null,
                "proposed_end": null,
                "estimated_start": null,
                "estimated_end": null,
                "actual_start": null,
                "actual_end": null,
                "proposed_duration_timestamp": null,
                "estimated_duration_timestamp": null,
                "actual_duration_timestamp": null,
                "progress": "0",
                "priority_score": "0"
                },
                "parents": [],
                "children": []
            },
            "21": {
                "itemDetails": {
                "id": "21",
                "parent_id": "11",
                "tags": "task",
                "title": "Create the checkout page",
                "content": null,
                "status": "backlog",
                "next_progressive_status":  "in-progress",
                "assigned_to": "john",
                "importance": null,
                "added_value": null,
                "proposed_start": null,
                "proposed_end": null,
                "estimated_start": null,
                "estimated_end": null,
                "actual_start": null,
                "actual_end": null,
                "proposed_duration_timestamp": null,
                "estimated_duration_timestamp": null,
                "actual_duration_timestamp": null,
                "progress": "0",
                "priority_score": "0"
                },
                "parents": [],
                "children": []
            }
            }
        },
        "12": {
            "itemDetails": {
            "id": "12",
            "parent_id": "8",
            "tags": "objective",
            "title": "Develop CRM system",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": null,
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": []
        },
        "25": {
            "itemDetails": {
            "id": "25",
            "parent_id": "8",
            "tags": "folder",
            "title": "Testing",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": null,
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": {
            "26": {
                "itemDetails": {
                "id": "26",
                "parent_id": "25",
                "tags": "task",
                "title": "Load test for high traffic",
                "content": null,
                "status": "backlog",
                "next_progressive_status":  "in-progress",
                "assigned_to": "john",
                "importance": null,
                "added_value": null,
                "proposed_start": "2022-07-24 00:01:00",
                "proposed_end": "2022-07-25 23:59:00",
                "estimated_start": null,
                "estimated_end": null,
                "actual_start": null,
                "actual_end": null,
                "proposed_duration_timestamp": "18000",
                "estimated_duration_timestamp": null,
                "actual_duration_timestamp": null,
                "progress": "0",
                "priority_score": "2.998282967033"
                },
                "parents": [],
                "children": []
            }
            }
        }
        }
    },
    "9": {
        "itemDetails": {
        "id": "9",
        "parent_id": "1",
        "tags": "folder",
        "title": "Infrastructure",
        "content": null,
        "status": "backlog",
        "next_progressive_status":  "in-progress",
        "assigned_to": "john",
        "importance": null,
        "added_value": null,
        "proposed_start": null,
        "proposed_end": null,
        "estimated_start": null,
        "estimated_end": null,
        "actual_start": null,
        "actual_end": null,
        "proposed_duration_timestamp": null,
        "estimated_duration_timestamp": null,
        "actual_duration_timestamp": null,
        "progress": "0",
        "priority_score": "0"
        },
        "parents": [],
        "children": {
        "10": {
            "itemDetails": {
            "id": "10",
            "parent_id": "9",
            "tags": "task",
            "title": "Setup CI\/CD pipline",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": "2022-07-17 00:01:00",
            "proposed_end": "2022-07-22 23:59:00",
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": "72000",
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "2.9931318681319"
            },
            "children": []
        },
        "22": {
            "itemDetails": {
            "id": "22",
            "parent_id": "9",
            "tags": "folder",
            "title": "Setup servers",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "john",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": null,
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": {
            "23": {
                "itemDetails": {
                "id": "23",
                "parent_id": "22",
                "tags": "task",
                "title": "Setup app servers",
                "content": null,
                "status": "backlog",
                "next_progressive_status":  "in-progress",
                "assigned_to": "john",
                "importance": null,
                "added_value": null,
                "proposed_start": null,
                "proposed_end": null,
                "estimated_start": null,
                "estimated_end": null,
                "actual_start": null,
                "actual_end": null,
                "proposed_duration_timestamp": null,
                "estimated_duration_timestamp": null,
                "actual_duration_timestamp": null,
                "progress": "0",
                "priority_score": "0"
                },
                "parents": [],
                "children": []
            },
            "24": {
                "itemDetails": {
                "id": "24",
                "parent_id": "22",
                "tags": "task",
                "title": "Setup data servers",
                "content": null,
                "status": "backlog",
                "next_progressive_status":  "in-progress",
                "assigned_to": "john",
                "importance": null,
                "added_value": null,
                "proposed_start": null,
                "proposed_end": null,
                "estimated_start": null,
                "estimated_end": null,
                "actual_start": null,
                "actual_end": null,
                "proposed_duration_timestamp": null,
                "estimated_duration_timestamp": null,
                "actual_duration_timestamp": null,
                "progress": "0",
                "priority_score": "0"
                },
                "parents": [],
                "children": []
            }
            }
        }
        }
    },
    "27": {
        "itemDetails": {
        "id": "27",
        "parent_id": "1",
        "tags": "folder",
        "title": "Deployment",
        "content": null,
        "status": "backlog",
        "next_progressive_status":  "in-progress",
        "assigned_to": "doe",
        "importance": null,
        "added_value": null,
        "proposed_start": null,
        "proposed_end": null,
        "estimated_start": null,
        "estimated_end": null,
        "actual_start": null,
        "actual_end": null,
        "proposed_duration_timestamp": null,
        "estimated_duration_timestamp": null,
        "actual_duration_timestamp": null,
        "progress": "0",
        "priority_score": "0"
        },
        "parents": [],
        "children": {
        "28": {
            "itemDetails": {
            "id": "28",
            "parent_id": "27",
            "tags": "task",
            "title": "Begin marketing campaign",
            "content": null,
            "status": "backlog",
            "next_progressive_status":  "in-progress",
            "assigned_to": "doe",
            "importance": null,
            "added_value": null,
            "proposed_start": null,
            "proposed_end": null,
            "estimated_start": null,
            "estimated_end": null,
            "actual_start": null,
            "actual_end": null,
            "proposed_duration_timestamp": null,
            "estimated_duration_timestamp": null,
            "actual_duration_timestamp": null,
            "progress": "0",
            "priority_score": "0"
            },
            "children": []
        }
        }
    }
    }
}
}`

const dataArray = JSON.parse(data);

export default dataArray;